// Help: plain-language FAQ for learners who get stuck on a module. Offline, bilingual, glossary-linked.
import { t, tt } from "../i18n.js";
import { esc, icon } from "../ui.js";
import { gl } from "../glossary.js";
import { state } from "../state.js";

const FAQ = [
  { q: { en: "The link opens a page in English only and I read Hindi better", hi: "लिंक सिर्फ़ अंग्रेज़ी पेज खोलता है और मैं हिंदी बेहतर पढ़ता/पढ़ती हूं" },
    a: { en: "Look at the card's language tag: steps marked \"Hindi available\" have Hindi versions (Spoken Tutorial, freeCodeCamp Hindi, NPTEL Hindi). For English pages, turn on Chrome's page translate (three dots → Translate) for menus, but keep code and commands in English. Read one short section, write its meaning in Hindi in your notes, then continue. If a step stays too hard, mark it done after the checkpoint and choose \"Too hard\": a simpler step is added automatically.", hi: "कार्ड का भाषा टैग देखें: \"हिंदी उपलब्ध\" वाले कदमों के हिंदी संस्करण हैं (Spoken Tutorial, freeCodeCamp Hindi, NPTEL Hindi)। अंग्रेज़ी पेज के लिए Chrome का पेज अनुवाद चालू करें (तीन बिंदु → Translate), पर कोड और कमांड अंग्रेज़ी में रखें। एक छोटा हिस्सा पढ़ें, उसका अर्थ हिंदी में नोट करें, फिर आगे बढ़ें। कदम बहुत कठिन रहे तो चेकपॉइंट के बाद पूरा करें और \"बहुत कठिन\" चुनें: एक सरल कदम अपने आप जुड़ जाएगा।" } },
  { q: { en: "The site asks me to pay or shows a locked lesson", hi: "साइट पैसे मांगती है या बंद पाठ दिखाती है" },
    a: { en: "Every resource here is free to learn. \"Free to audit\" means you can watch and read everything but a certificate costs money: you do not need the certificate. \"Free part only\" means some later lessons are paid: finish the free part and move on. Never enter card details for a step in this app. If you hit a paywall before the free part ends, tap \"Find a free resource\" in the skills panel or use \"Too hard\" to get an alternative.", hi: "यहां हर संसाधन सीखने के लिए मुफ़्त है। \"ऑडिट मुफ़्त\" का मतलब सब देख-पढ़ सकते हैं पर सर्टिफ़िकेट के पैसे लगते हैं: सर्टिफ़िकेट ज़रूरी नहीं। \"सिर्फ़ मुफ़्त हिस्सा\" का मतलब कुछ बाद के पाठ पेड हैं: मुफ़्त हिस्सा पूरा कर आगे बढ़ें। इस ऐप के किसी कदम के लिए कभी कार्ड विवरण न डालें। मुफ़्त हिस्से से पहले पेवॉल आए तो स्किल पैनल में \"मुफ़्त संसाधन ढूंढें\" दबाएं या \"बहुत कठिन\" से विकल्प पाएं।" } },
  { q: { en: "It says create an account. Is that safe?", hi: "यह खाता बनाने को कहता है। क्या यह सुरक्षित है?" },
    a: { en: "Steps tagged \"Free with account\" need a sign-up so the site can save your progress. Use your email or Google login, a unique password, and never your bank details. If you have no email yet, the tooling-basics step \"GCFGlobal Email Basics\" shows how to make one in ten minutes.", hi: "\"खाते के साथ मुफ़्त\" वाले कदमों में साइन-अप चाहिए ताकि साइट आपकी प्रगति सहेज सके। अपना ईमेल या Google लॉगिन, अनोखा पासवर्ड इस्तेमाल करें, बैंक विवरण कभी नहीं। ईमेल न हो तो टूलिंग बेसिक्स का कदम \"GCFGlobal Email Basics\" दस मिनट में बनाना सिखाता है।" } },
  { q: { en: "I only have a phone and the step says it needs a computer", hi: "मेरे पास सिर्फ़ फ़ोन है और कदम कहता है कंप्यूटर चाहिए" },
    a: { en: "Steps marked \"Needs a computer\" are placed later in your path on purpose. Options: a library or community centre computer for one to two hours a week; a friend's laptop for the checkpoint only; or phone apps that run code, such as Replit or Acode for HTML/CSS/JS and Python, and Termux for a Linux terminal. Watch the lessons on your phone first and do the hands-on part when you have the computer.", hi: "\"कंप्यूटर चाहिए\" वाले कदम जानबूझकर आपके रास्ते में बाद में रखे जाते हैं। विकल्प: हफ़्ते में एक-दो घंटे लाइब्रेरी या सामुदायिक केंद्र का कंप्यूटर; सिर्फ़ चेकपॉइंट के लिए दोस्त का लैपटॉप; या कोड चलाने वाले फ़ोन ऐप जैसे HTML/CSS/JS और Python के लिए Replit या Acode, और Linux टर्मिनल के लिए Termux। पाठ पहले फ़ोन पर देखें और हाथ का काम कंप्यूटर मिलने पर करें।" } },
  { q: { en: "I do not understand a word in the lesson", hi: "पाठ का कोई शब्द समझ नहीं आता" },
    a: { en: "Underlined words anywhere in this app open a plain-language explanation when you tap them, for example file, account, browser, command, Git. For words inside the lesson itself, type the word plus \"meaning in Hindi\" in a search, or paste one sentence into Claude and ask for a one-line explanation for a beginner.", hi: "इस ऐप में कहीं भी रेखांकित शब्द टैप करने पर सरल व्याख्या खुलती है, जैसे file, account, browser, command, Git। पाठ के अंदर के शब्दों के लिए सर्च में शब्द + \"meaning in Hindi\" लिखें, या एक वाक्य Claude में चिपकाकर शुरुआती के लिए एक-पंक्ति व्याख्या मांगें।" } },
  { q: { en: "I am stuck on the checkpoint. What counts as done?", hi: "मैं चेकपॉइंट पर अटक गया/गई। पूरा कब माना जाएगा?" },
    a: { en: "Each checkpoint box is a yes/no you can check yourself: it runs, it matches the stated outcome, you can explain it in your own words. Do the smallest version first, for example one page instead of a site, ten rows instead of a full sheet. Keep proof: a screenshot, a file, or a link. If two steps in a row feel too hard, say so with the rating buttons and the path adds a reinforcing step before you continue.", hi: "हर चेकपॉइंट बॉक्स एक हां/नहीं है जिसे आप खुद जांच सकते हैं: यह चलता है, बताए परिणाम से मेल खाता है, आप इसे अपने शब्दों में समझा सकते हैं। पहले सबसे छोटा संस्करण बनाएं, जैसे साइट के बजाय एक पेज, पूरी शीट के बजाय दस पंक्तियां। सबूत रखें: स्क्रीनशॉट, फ़ाइल या लिंक। लगातार दो कदम बहुत कठिन लगें तो रेटिंग बटन से बताएं और रास्ता आगे बढ़ने से पहले मज़बूत करने वाला कदम जोड़ देगा।" } },
  { q: { en: "Where do I save my project files so I can find them again?", hi: "अपने प्रोजेक्ट की फ़ाइलें कहां सहेजूं ताकि दोबारा मिलें?" },
    a: { en: "Make one folder named after this app, with one sub-folder per step (for example 01-html-foundations). Save everything for that step inside it. On a phone, use the Files app; back the folder up to Google Drive once a week. For code, the Git step teaches you to push the folder to GitHub, which is both a backup and a portfolio.", hi: "इस ऐप के नाम से एक फ़ोल्डर बनाएं, हर कदम के लिए एक सब-फ़ोल्डर (जैसे 01-html-foundations)। उस कदम की हर चीज़ उसी में सहेजें। फ़ोन पर Files ऐप उपयोग करें; हफ़्ते में एक बार फ़ोल्डर Google Drive पर बैकअप करें। कोड के लिए Git का कदम फ़ोल्डर को GitHub पर पुश करना सिखाता है, जो बैकअप और पोर्टफ़ोलियो दोनों है।" } },
  { q: { en: "My internet is slow or I have no data at home", hi: "मेरा इंटरनेट धीमा है या घर पर डेटा नहीं है" },
    a: { en: "This app works offline after the first load, so your plan and checkpoints are always available. For lessons: download videos on Wi-Fi at a library, college or centre (YouTube's Download button, or the Spoken Tutorial offline packs), and prefer text-based steps tagged \"Phone-friendly\", which use very little data. Read and take notes offline; use data only to submit or search.", hi: "पहली लोड के बाद यह ऐप ऑफ़लाइन चलता है, इसलिए आपकी योजना और चेकपॉइंट हमेशा उपलब्ध हैं। पाठों के लिए: लाइब्रेरी, कॉलेज या केंद्र के Wi-Fi पर वीडियो डाउनलोड करें (YouTube का Download बटन, या Spoken Tutorial के ऑफ़लाइन पैक), और \"फ़ोन पर ठीक\" वाले टेक्स्ट-आधारित कदम चुनें जो बहुत कम डेटा लेते हैं। ऑफ़लाइन पढ़ें और नोट्स बनाएं; डेटा सिर्फ़ जमा करने या खोजने के लिए।" } },
  { q: { en: "The link is broken or the page has moved", hi: "लिंक टूटा है या पेज हट गया है" },
    a: { en: "Cards tagged \"Link may have moved\" were flagged when the catalogue was checked. Search the resource name plus the platform (for example \"Foundations HTML The Odin Project\"); the course is usually still there under a new address. If it is truly gone, use \"Find a free resource\" on the matching skill to pick a replacement from the catalogue.", hi: "\"लिंक शायद बदल गया है\" वाले कार्ड कैटलॉग जांच के समय चिह्नित हुए थे। संसाधन का नाम और प्लेटफ़ॉर्म खोजें (जैसे \"Foundations HTML The Odin Project\"); कोर्स आमतौर पर नए पते पर मौजूद होता है। सचमुच हट गया हो तो मिलती-जुलती स्किल पर \"मुफ़्त संसाधन ढूंढें\" से कैटलॉग से विकल्प चुनें।" } },
  { q: { en: "How do I take a screenshot as proof?", hi: "सबूत के लिए स्क्रीनशॉट कैसे लूं?" },
    a: { en: "Android: press Power and Volume Down together. iPhone: Side button and Volume Up. Windows: Win+Shift+S, then click and drag. The image lands in Photos or Pictures/Screenshots. Rename it with the step number, for example 03-checkpoint.png, and keep it in that step's folder.", hi: "Android: Power और Volume Down साथ दबाएं। iPhone: Side बटन और Volume Up। Windows: Win+Shift+S, फिर खींचें। इमेज Photos या Pictures/Screenshots में जाती है। इसे कदम की संख्या से नाम दें, जैसे 03-checkpoint.png, और उसी कदम के फ़ोल्डर में रखें।" } },
  { q: { en: "Where can I ask a person?", hi: "किसी व्यक्ति से कहां पूछूं?" },
    a: { en: "Print or share the mentor one-pager from your path and take it to a library, college lab, or community learning centre; it shows exactly where you are. Online: the freeCodeCamp forum and Discord (English and Hindi), Spoken Tutorial forums, and Stack Overflow for specific error messages (paste the exact error). For a fast first answer, use Ask Claude on your path.", hi: "अपने रास्ते से मेंटर एक-पेज सारांश प्रिंट या साझा करें और लाइब्रेरी, कॉलेज लैब या सामुदायिक शिक्षण केंद्र ले जाएं; यह दिखाता है आप ठीक कहां हैं। ऑनलाइन: freeCodeCamp फ़ोरम और Discord (अंग्रेज़ी और हिंदी), Spoken Tutorial फ़ोरम, और खास एरर संदेशों के लिए Stack Overflow (सटीक एरर चिपकाएं)। जल्दी पहले जवाब के लिए अपने रास्ते पर Ask Claude उपयोग करें।" } },
  { q: { en: "I lost my progress", hi: "मेरी प्रगति खो गई" },
    a: { en: "As a guest, your plan lives only in the current browser session. Tap \"Save plan to this device\" on your path so it survives closing the browser; use \"Resume saved plan\" on the home page to get it back. Clearing browser data deletes it, so also keep a copy of the one-pager.", hi: "अतिथि के रूप में आपकी योजना सिर्फ़ मौजूदा ब्राउज़र सत्र में रहती है। अपने रास्ते पर \"योजना इस डिवाइस पर सहेजें\" दबाएं ताकि ब्राउज़र बंद होने पर भी बची रहे; होम पेज पर \"सहेजी योजना जारी रखें\" से वापस पाएं। ब्राउज़र डेटा मिटाने से यह हट जाती है, इसलिए एक-पेज सारांश की प्रति भी रखें।" } },
];

export function render(root, ctx) {
  root.innerHTML = `
    <section class="glass card"><div class="tag accent" style="margin-bottom:8px">${icon("help")} ${esc(t("help"))}</div>
      <h1 style="font-size:1.4rem">${esc(t("helpTitle"))}</h1><p class="muted">${esc(t("helpLead"))}</p>
      ${FAQ.map((f, i) => `<details class="inner" style="margin-top:8px" ${i === 0 ? "open" : ""}><summary style="cursor:pointer;font-weight:600">${esc(tt(f.q))}</summary><p class="small" style="margin:8px 0 0">${gl(tt(f.a))}</p></details>`).join("")}
      <div class="row" style="margin-top:14px">
        <button class="btn btn-primary" data-go="${state.planReadyAt ? "dashboard" : "home"}">${icon("arrowLeft")} ${esc(state.planReadyAt ? t("dashboard") : t("home"))}</button>
        <button class="btn btn-ghost" data-go="about">${icon("book")} ${esc(t("about"))}</button>
      </div></section>`;
  root.querySelectorAll("[data-go]").forEach((b) => b.onclick = () => ctx.go(b.dataset.go));
}
